# Generated by Django 5.0.3 on 2024-03-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='tahun',
            field=models.IntegerField(null=True),
        ),
    ]
