# Generated by Django 5.0.3 on 2024-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_tahun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugasakhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('acc_ujian', models.ImageField(null=True, upload_to='bukti_acc_ujian/')),
                ('bebas_teori', models.ImageField(null=True, upload_to='bukti_bebas_teori/')),
                ('krs', models.ImageField(null=True, upload_to='bukti_krs/')),
                ('cek_plagiasi', models.ImageField(null=True, upload_to='bukti_hasil_cek-plagiasi/')),
                ('file_tugas_akhir', models.ImageField(null=True, upload_to='file_tugas_akhir/')),
                ('sk_diterima', models.ImageField(null=True, upload_to='sk_diterima/')),
                ('sk_selesai', models.ImageField(null=True, upload_to='sk_selesai/')),
                ('lembar_penilaian', models.ImageField(null=True, upload_to='lembar_penilian/')),
                ('kepemilikan_usaha', models.ImageField(null=True, upload_to='bukti_usaha/')),
                ('bukti_mou_spk', models.ImageField(null=True, upload_to='bukti_mou_spk/')),
                ('ijazah_terakhir', models.ImageField(null=True, upload_to='bukti_ijazah_terakhir/')),
                ('akte_kelahiran', models.ImageField(null=True, upload_to='bukti_akte_kelahiran/')),
                ('ktp_kk', models.ImageField(null=True, upload_to='bukti_ktp_kk/')),
                ('foto', models.ImageField(null=True, upload_to='pas_foto/')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
